/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) throws Exception {
        ReportGenerator reportGenerator = new ReportGenerator("/Users/jamesharrington/Repos/AdventOfCode2024/java/day02/app/src/main/java/org/example/input1.txt");

        System.out.println("Advent of Code: Day 1, Part 1 -- " + reportGenerator.howManySafe());
        System.out.println("Advent of Code: Day 1, Part 2 -- " + reportGenerator.howManySafeWithARemoval());
    }
}
