/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class Report {
    private List<Integer> levels;

    Report(String reportSummary) {
        levels = Arrays.stream(reportSummary.split(" ")).map(Integer::parseInt).toList();
    }

    public boolean isReportUnsafe() {
        return false;
    }

}
